# Generated by Django 4.0 on 2021-12-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0006_choice_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='pub_date',
        ),
    ]
