# Generated by Django 4.0 on 2021-12-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0010_choice_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
