# Generated by Django 4.0 on 2021-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0014_alter_choice_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
